//*****************************************************************************
//*****************************************************************************
//  FILENAME: TX8SW_1.h
//  Version: 1.30, Updated on 2015/3/4 at 22:27:54
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: TX8 User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef TX8SW_1_INCLUDE
#define TX8SW_1_INCLUDE

#include <m8c.h>

// Create pragmas to support proper argument and return value passing 
#pragma fastcall16  TX8SW_1_Start
#pragma fastcall16  TX8SW_1_Stop
#pragma fastcall16  TX8SW_1_SendData
#pragma fastcall16  TX8SW_1_PutString
#pragma fastcall16  TX8SW_1_CPutString
#pragma fastcall16  TX8SW_1_PutChar
#pragma fastcall16  TX8SW_1_Write
#pragma fastcall16  TX8SW_1_CWrite
#pragma fastcall16  TX8SW_1_PutSHexByte
#pragma fastcall16  TX8SW_1_PutSHexInt
#pragma fastcall16  TX8SW_1_PutCRLF

//-------------------------------------------------
// Prototypes of the TX8SW_1 API.
//-------------------------------------------------
// Low level TX functions
extern void  TX8SW_1_Start(void);
extern void  TX8SW_1_Stop(void);
extern void  TX8SW_1_SendData(BYTE bTxData);

// High level TX functions
extern void   TX8SW_1_PutString(BYTE * szRamString);
extern void   TX8SW_1_CPutString(const BYTE * szRomString);
extern void   TX8SW_1_PutChar(BYTE cData);
extern void   TX8SW_1_Write(BYTE * sRamData, BYTE bCount);
extern void   TX8SW_1_CWrite(const BYTE * sRomData, INT iCount);
extern void   TX8SW_1_PutSHexByte(BYTE bValue);
extern void   TX8SW_1_PutSHexInt(INT iValue);
extern void   TX8SW_1_PutCRLF(void);

#endif
// end of file TX8SW_1.h
