//*****************************************************************************
//*****************************************************************************
//  FILENAME: DIAG_OUT1.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: DIAG_OUT1 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef DIAG_OUT1_INCLUDE
#define DIAG_OUT1_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  DIAG_OUT1_Stop
#pragma fastcall16  DIAG_OUT1_Start
#pragma fastcall16  DIAG_OUT1_On
#pragma fastcall16  DIAG_OUT1_Off
#pragma fastcall16  DIAG_OUT1_Switch
#pragma fastcall16  DIAG_OUT1_Invert
#pragma fastcall16  DIAG_OUT1_GetState


//-------------------------------------------------
// Constants for DIAG_OUT1 API's.
//-------------------------------------------------
//
#define  DIAG_OUT1_ON   1
#define  DIAG_OUT1_OFF  0

//-------------------------------------------------
// Prototypes of the DIAG_OUT1 API.
//-------------------------------------------------
extern void  DIAG_OUT1_Start(void);                                     
extern void  DIAG_OUT1_Stop(void);                                      
extern void  DIAG_OUT1_On(void);                                      
extern void  DIAG_OUT1_Off(void);                                      
extern void  DIAG_OUT1_Switch(BYTE bSwitch);
extern void  DIAG_OUT1_Invert(void);                                         
extern BYTE  DIAG_OUT1_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
