/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
/*
*   PSoCGPIOINT.h
*   Data: 04 June, 2002
*   Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
*
*  This file is generated by the Device Editor on Application Generation.
*  It contains equates that are useful in writing code relating to GPIO
*  related values.
*  
*  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
*  Edits to this file will not be preserved.
*/
// IRQPin address and mask defines
#pragma	ioport	IRQPin_Data_ADDR:	0x0
BYTE			IRQPin_Data_ADDR;
#pragma	ioport	IRQPin_DriveMode_0_ADDR:	0x100
BYTE			IRQPin_DriveMode_0_ADDR;
#pragma	ioport	IRQPin_DriveMode_1_ADDR:	0x101
BYTE			IRQPin_DriveMode_1_ADDR;
#pragma	ioport	IRQPin_DriveMode_2_ADDR:	0x3
BYTE			IRQPin_DriveMode_2_ADDR;
#pragma	ioport	IRQPin_GlobalSelect_ADDR:	0x2
BYTE			IRQPin_GlobalSelect_ADDR;
#pragma	ioport	IRQPin_IntCtrl_0_ADDR:	0x102
BYTE			IRQPin_IntCtrl_0_ADDR;
#pragma	ioport	IRQPin_IntCtrl_1_ADDR:	0x103
BYTE			IRQPin_IntCtrl_1_ADDR;
#pragma	ioport	IRQPin_IntEn_ADDR:	0x1
BYTE			IRQPin_IntEn_ADDR;
#define IRQPin_MASK 0x40
#pragma	ioport	IRQPin_MUXBusCtrl_ADDR:	0x1d8
BYTE			IRQPin_MUXBusCtrl_ADDR;
// IRQPin Shadow defines
//   IRQPin_DataShadow define
extern unsigned char Port_0_Data_SHADE;
#define IRQPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// MISOPin address and mask defines
#pragma	ioport	MISOPin_Data_ADDR:	0x0
BYTE			MISOPin_Data_ADDR;
#pragma	ioport	MISOPin_DriveMode_0_ADDR:	0x100
BYTE			MISOPin_DriveMode_0_ADDR;
#pragma	ioport	MISOPin_DriveMode_1_ADDR:	0x101
BYTE			MISOPin_DriveMode_1_ADDR;
#pragma	ioport	MISOPin_DriveMode_2_ADDR:	0x3
BYTE			MISOPin_DriveMode_2_ADDR;
#pragma	ioport	MISOPin_GlobalSelect_ADDR:	0x2
BYTE			MISOPin_GlobalSelect_ADDR;
#pragma	ioport	MISOPin_IntCtrl_0_ADDR:	0x102
BYTE			MISOPin_IntCtrl_0_ADDR;
#pragma	ioport	MISOPin_IntCtrl_1_ADDR:	0x103
BYTE			MISOPin_IntCtrl_1_ADDR;
#pragma	ioport	MISOPin_IntEn_ADDR:	0x1
BYTE			MISOPin_IntEn_ADDR;
#define MISOPin_MASK 0x1
#pragma	ioport	MISOPin_MUXBusCtrl_ADDR:	0x1d8
BYTE			MISOPin_MUXBusCtrl_ADDR;
// MISOPin Shadow defines
//   MISOPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define MISOPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// SCK_Pin address and mask defines
#pragma	ioport	SCK_Pin_Data_ADDR:	0x0
BYTE			SCK_Pin_Data_ADDR;
#pragma	ioport	SCK_Pin_DriveMode_0_ADDR:	0x100
BYTE			SCK_Pin_DriveMode_0_ADDR;
#pragma	ioport	SCK_Pin_DriveMode_1_ADDR:	0x101
BYTE			SCK_Pin_DriveMode_1_ADDR;
#pragma	ioport	SCK_Pin_DriveMode_2_ADDR:	0x3
BYTE			SCK_Pin_DriveMode_2_ADDR;
#pragma	ioport	SCK_Pin_GlobalSelect_ADDR:	0x2
BYTE			SCK_Pin_GlobalSelect_ADDR;
#pragma	ioport	SCK_Pin_IntCtrl_0_ADDR:	0x102
BYTE			SCK_Pin_IntCtrl_0_ADDR;
#pragma	ioport	SCK_Pin_IntCtrl_1_ADDR:	0x103
BYTE			SCK_Pin_IntCtrl_1_ADDR;
#pragma	ioport	SCK_Pin_IntEn_ADDR:	0x1
BYTE			SCK_Pin_IntEn_ADDR;
#define SCK_Pin_MASK 0x8
#pragma	ioport	SCK_Pin_MUXBusCtrl_ADDR:	0x1d8
BYTE			SCK_Pin_MUXBusCtrl_ADDR;
// SCK_Pin Shadow defines
//   SCK_Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define SCK_Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// RSTPin address and mask defines
#pragma	ioport	RSTPin_Data_ADDR:	0x0
BYTE			RSTPin_Data_ADDR;
#pragma	ioport	RSTPin_DriveMode_0_ADDR:	0x100
BYTE			RSTPin_DriveMode_0_ADDR;
#pragma	ioport	RSTPin_DriveMode_1_ADDR:	0x101
BYTE			RSTPin_DriveMode_1_ADDR;
#pragma	ioport	RSTPin_DriveMode_2_ADDR:	0x3
BYTE			RSTPin_DriveMode_2_ADDR;
#pragma	ioport	RSTPin_GlobalSelect_ADDR:	0x2
BYTE			RSTPin_GlobalSelect_ADDR;
#pragma	ioport	RSTPin_IntCtrl_0_ADDR:	0x102
BYTE			RSTPin_IntCtrl_0_ADDR;
#pragma	ioport	RSTPin_IntCtrl_1_ADDR:	0x103
BYTE			RSTPin_IntCtrl_1_ADDR;
#pragma	ioport	RSTPin_IntEn_ADDR:	0x1
BYTE			RSTPin_IntEn_ADDR;
#define RSTPin_MASK 0x10
#pragma	ioport	RSTPin_MUXBusCtrl_ADDR:	0x1d8
BYTE			RSTPin_MUXBusCtrl_ADDR;
// RSTPin Shadow defines
//   RSTPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define RSTPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// MOSI_Pin address and mask defines
#pragma	ioport	MOSI_Pin_Data_ADDR:	0x0
BYTE			MOSI_Pin_Data_ADDR;
#pragma	ioport	MOSI_Pin_DriveMode_0_ADDR:	0x100
BYTE			MOSI_Pin_DriveMode_0_ADDR;
#pragma	ioport	MOSI_Pin_DriveMode_1_ADDR:	0x101
BYTE			MOSI_Pin_DriveMode_1_ADDR;
#pragma	ioport	MOSI_Pin_DriveMode_2_ADDR:	0x3
BYTE			MOSI_Pin_DriveMode_2_ADDR;
#pragma	ioport	MOSI_Pin_GlobalSelect_ADDR:	0x2
BYTE			MOSI_Pin_GlobalSelect_ADDR;
#pragma	ioport	MOSI_Pin_IntCtrl_0_ADDR:	0x102
BYTE			MOSI_Pin_IntCtrl_0_ADDR;
#pragma	ioport	MOSI_Pin_IntCtrl_1_ADDR:	0x103
BYTE			MOSI_Pin_IntCtrl_1_ADDR;
#pragma	ioport	MOSI_Pin_IntEn_ADDR:	0x1
BYTE			MOSI_Pin_IntEn_ADDR;
#define MOSI_Pin_MASK 0x20
#pragma	ioport	MOSI_Pin_MUXBusCtrl_ADDR:	0x1d8
BYTE			MOSI_Pin_MUXBusCtrl_ADDR;
// MOSI_Pin Shadow defines
//   MOSI_Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define MOSI_Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CS_PINPin address and mask defines
#pragma	ioport	CS_PINPin_Data_ADDR:	0x0
BYTE			CS_PINPin_Data_ADDR;
#pragma	ioport	CS_PINPin_DriveMode_0_ADDR:	0x100
BYTE			CS_PINPin_DriveMode_0_ADDR;
#pragma	ioport	CS_PINPin_DriveMode_1_ADDR:	0x101
BYTE			CS_PINPin_DriveMode_1_ADDR;
#pragma	ioport	CS_PINPin_DriveMode_2_ADDR:	0x3
BYTE			CS_PINPin_DriveMode_2_ADDR;
#pragma	ioport	CS_PINPin_GlobalSelect_ADDR:	0x2
BYTE			CS_PINPin_GlobalSelect_ADDR;
#pragma	ioport	CS_PINPin_IntCtrl_0_ADDR:	0x102
BYTE			CS_PINPin_IntCtrl_0_ADDR;
#pragma	ioport	CS_PINPin_IntCtrl_1_ADDR:	0x103
BYTE			CS_PINPin_IntCtrl_1_ADDR;
#pragma	ioport	CS_PINPin_IntEn_ADDR:	0x1
BYTE			CS_PINPin_IntEn_ADDR;
#define CS_PINPin_MASK 0x80
#pragma	ioport	CS_PINPin_MUXBusCtrl_ADDR:	0x1d8
BYTE			CS_PINPin_MUXBusCtrl_ADDR;
// CS_PINPin Shadow defines
//   CS_PINPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CS_PINPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// TX8SW_1Pin address and mask defines
#pragma	ioport	TX8SW_1Pin_Data_ADDR:	0x4
BYTE			TX8SW_1Pin_Data_ADDR;
#pragma	ioport	TX8SW_1Pin_DriveMode_0_ADDR:	0x104
BYTE			TX8SW_1Pin_DriveMode_0_ADDR;
#pragma	ioport	TX8SW_1Pin_DriveMode_1_ADDR:	0x105
BYTE			TX8SW_1Pin_DriveMode_1_ADDR;
#pragma	ioport	TX8SW_1Pin_DriveMode_2_ADDR:	0x7
BYTE			TX8SW_1Pin_DriveMode_2_ADDR;
#pragma	ioport	TX8SW_1Pin_GlobalSelect_ADDR:	0x6
BYTE			TX8SW_1Pin_GlobalSelect_ADDR;
#pragma	ioport	TX8SW_1Pin_IntCtrl_0_ADDR:	0x106
BYTE			TX8SW_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	TX8SW_1Pin_IntCtrl_1_ADDR:	0x107
BYTE			TX8SW_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	TX8SW_1Pin_IntEn_ADDR:	0x5
BYTE			TX8SW_1Pin_IntEn_ADDR;
#define TX8SW_1Pin_MASK 0x2
#pragma	ioport	TX8SW_1Pin_MUXBusCtrl_ADDR:	0x1d9
BYTE			TX8SW_1Pin_MUXBusCtrl_ADDR;
// TX8SW_1Pin Shadow defines
//   TX8SW_1Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define TX8SW_1Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// TXDPin address and mask defines
#pragma	ioport	TXDPin_Data_ADDR:	0x4
BYTE			TXDPin_Data_ADDR;
#pragma	ioport	TXDPin_DriveMode_0_ADDR:	0x104
BYTE			TXDPin_DriveMode_0_ADDR;
#pragma	ioport	TXDPin_DriveMode_1_ADDR:	0x105
BYTE			TXDPin_DriveMode_1_ADDR;
#pragma	ioport	TXDPin_DriveMode_2_ADDR:	0x7
BYTE			TXDPin_DriveMode_2_ADDR;
#pragma	ioport	TXDPin_GlobalSelect_ADDR:	0x6
BYTE			TXDPin_GlobalSelect_ADDR;
#pragma	ioport	TXDPin_IntCtrl_0_ADDR:	0x106
BYTE			TXDPin_IntCtrl_0_ADDR;
#pragma	ioport	TXDPin_IntCtrl_1_ADDR:	0x107
BYTE			TXDPin_IntCtrl_1_ADDR;
#pragma	ioport	TXDPin_IntEn_ADDR:	0x5
BYTE			TXDPin_IntEn_ADDR;
#define TXDPin_MASK 0x10
#pragma	ioport	TXDPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			TXDPin_MUXBusCtrl_ADDR;
// TXDPin Shadow defines
//   TXDPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define TXDPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0xc
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x10c
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x10d
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0xf
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0xe
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x10e
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x10f
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0xd
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x1
#pragma	ioport	LED_1Pin_MUXBusCtrl_ADDR:	0x1db
BYTE			LED_1Pin_MUXBusCtrl_ADDR;
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
